FROM node:24.13.0-bookworm-slim AS build

LABEL org.opencontainers.image.source=https://github.com/labiraus/homelab

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:24.13.0-bookworm-slim

LABEL org.opencontainers.image.source=https://github.com/labiraus/homelab

WORKDIR /app

COPY package.json ./
RUN npm install --omit=dev

COPY --from=build /app/dist ./dist

EXPOSE 8080

CMD ["node", "dist/src/index.js"]
