{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "commonapi.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: {{ include "commonapi.fullname" . }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: {{ .Values.keda.natsJetStream.natsServerMonitoringEndpoint | quote }}
        account: {{ .Values.keda.natsJetStream.account | quote }}
        stream: {{ .Values.keda.natsJetStream.stream | quote }}
        consumer: {{ .Values.keda.natsJetStream.consumer | quote }}
        lagThreshold: {{ .Values.keda.natsJetStream.lagThreshold | quote }}
{{- end }}
