configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      default: true
      config:
        region: us-east-1
        s3Url: http://svartalfheim:9000
        s3ForcePathStyle: "true"
        insecureSkipTLSVerify: "false"
credentials:
  useSecret: true
  existingSecret: velero-minio-credentials
deployNodeAgent: true
snapshotsEnabled: false
