email: admin@labiraus.com # EDIT THIS
http01IngressClass: istio
certificate:
  namespace: istio-ingress
  name: mcp-labiraus-com
  secretName: mcp-labiraus-com-tls
  issuerName: letsencrypt-namecheap-dns01
  issuerKind: ClusterIssuer
  dnsNames:
    - mcp.labiraus.com # EDIT THIS
namecheap:
  enabled: true
  groupName: acme.labiraus.com # EDIT THIS
  apiSecretName: namecheap-api-credentials
