namespace: static-sites
site:
  name: foo
  host: site-foo.labiraus.com # EDIT THIS
gateway:
  name: public-gateway
  namespace: istio-ingress
minio:
  serviceName: homelab-hl
  namespace: minio
  port: 80
