apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: homelab

deploy:
  helm:
    releases:
      - name: flux-bootstrap
        chartPath: helm/infra/flux-bootstrap
        valuesFiles:
          - helm/infra/flux-bootstrap/values-ghcr.yaml
        namespace: homelab
        createNamespace: true
        wait: true
