apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.debug.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.debug.deploymentName }}
  ports:
    - name: ftp
      port: {{ int .Values.debug.ftp.port }}
      targetPort: ftp
      protocol: TCP
    {{- $pasvMin := int .Values.debug.ftp.passiveMinPort }}
    {{- $pasvStop := int (add (int .Values.debug.ftp.passiveMaxPort) 1) }}
    {{- range $port := untilStep $pasvMin $pasvStop 1 }}
    - name: pasv-{{ $port }}
      port: {{ $port }}
      targetPort: pasv-{{ $port }}
      protocol: TCP
    {{- end }}
