{{- $secretName := .Values.debug.ftp.authSecretName -}}
{{- $userKey := .Values.debug.ftp.userSecretKey -}}
{{- $passKey := .Values.debug.ftp.passwordSecretKey -}}
{{- if $secretName }}
{{- $existing := lookup "v1" "Secret" .Values.namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{ $userKey }}: {{- if and $existing (hasKey $existing.data $userKey) }} {{ index $existing.data $userKey | quote }}{{- else }} {{ .Values.debug.ftp.user | b64enc | quote }}{{- end }}
  {{ $passKey }}: {{- if and $existing (hasKey $existing.data $passKey) }} {{ index $existing.data $passKey | quote }}{{- else }} {{ randAlphaNum 24 | b64enc | quote }}{{- end }}
{{- end }}
