apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.debug.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.debug.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.debug.deploymentName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.debug.deploymentName }}
    spec:
      containers:
        - name: ftp
          image: "{{ .Values.debug.image.repository }}:{{ .Values.debug.image.tag }}"
          imagePullPolicy: {{ .Values.debug.image.pullPolicy }}
          env:
            - name: FTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.debug.ftp.authSecretName }}
                  key: {{ .Values.debug.ftp.userSecretKey }}
            - name: FTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.debug.ftp.authSecretName }}
                  key: {{ .Values.debug.ftp.passwordSecretKey }}
            - name: PASV_ADDRESS
              value: {{ .Values.debug.ftp.passiveAddress | quote }}
            - name: PASV_MIN_PORT
              value: {{ .Values.debug.ftp.passiveMinPort | quote }}
            - name: PASV_MAX_PORT
              value: {{ .Values.debug.ftp.passiveMaxPort | quote }}
            - name: LOG_STDOUT
              value: "YES"
            - name: FILE_OPEN_MODE
              value: "0666"
            - name: LOCAL_UMASK
              value: "022"
          ports:
            - name: ftp
              containerPort: {{ int .Values.debug.ftp.port }}
              protocol: TCP
            {{- $pasvMin := int .Values.debug.ftp.passiveMinPort }}
            {{- $pasvStop := int (add (int .Values.debug.ftp.passiveMaxPort) 1) }}
            {{- range $port := untilStep $pasvMin $pasvStop 1 }}
            - name: pasv-{{ $port }}
              containerPort: {{ $port }}
              protocol: TCP
            {{- end }}
          volumeMounts:
            - name: minecraft-data
              mountPath: /home/vsftpd/{{ .Values.debug.ftp.user }}
      volumes:
        - name: minecraft-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName }}
