{{- $local := .Values.persistence.local | default dict -}}
{{- if ($local.enabled | default false) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $local.volumeName | default "minecraft-local-pv" }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ $local.storageClassName | default "minecraft-local" }}
  local:
    path: {{ $local.path | default "/var/lib/minecraft-local" }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ $local.nodeName | default "jotunheim" }}
{{- end }}
