{{- if .Values.route.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: minecraft
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.route.gatewayName }}
      namespace: {{ .Values.route.gatewayNamespace }}
      sectionName: {{ .Values.route.sectionName }}
  rules:
    - backendRefs:
        - name: {{ .Values.service.name }}
          port: {{ .Values.server.port }}
{{- end }}
