---
kubernetes_manual_node_control_plane_host: yggdrasil
kubernetes_manual_node_kube_minor_channel: v1.34
kubernetes_manual_node_packages:
  - ca-certificates
  - curl
  - gpg
  - apt-transport-https
  - containerd
  - conntrack
  - pciutils
kubernetes_manual_node_kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl
kubernetes_manual_node_kubernetes_node_name: "{{ inventory_hostname }}"
kubernetes_manual_node_enable_nvidia_gpu: false
kubernetes_manual_node_nvidia_container_toolkit_packages:
  - nvidia-container-toolkit
kubernetes_manual_node_nvidia_runtime_class_name: nvidia
kubernetes_manual_node_nvidia_device_plugin_namespace: kube-system
kubernetes_manual_node_nvidia_device_plugin_name: nvidia-device-plugin
kubernetes_manual_node_nvidia_device_plugin_image: nvcr.io/nvidia/k8s-device-plugin:v0.17.1
kubernetes_manual_node_nvidia_selector_label_key: gpu.nvidia.com/device-plugin
kubernetes_manual_node_nvidia_selector_label_value: "true"
kubernetes_manual_node_gpu_labels: {}
kubernetes_manual_node_wait_for_node_registration: true
kubernetes_manual_node_wait_for_node_registration_retries: 30
kubernetes_manual_node_wait_for_node_registration_delay: 10
kubernetes_manual_node_headless: false
kubernetes_manual_node_headless_disable_services: []
kubernetes_manual_node_headless_purge_packages: []
