namespace: homelab
namespaces:
  - name: homelab
    labels:
      istio-injection: "enabled"
provider: generic
tag: uat
secret: true
image:
  repository:
min_version: 0.0.0-0
releases:
  - name: goapi
    type: oci
    namespace: homelab

  - name: pythonapi
    type: oci
    namespace: homelab

  - name: reactapp
    type: oci
    namespace: homelab
