# imagePullSecrets:
#   - name: ecr-registry-secret
podLabels: {}

image:
  tag: "uat"

ingress:
 enabled: true
 className: ""
 annotations: {}
 hosts:
  - host: uat.labiraus.com
    paths:
     - path: /go
       pathType: PathPrefix
       rewrite:          
         path:
           type: ReplacePrefixMatch
           replacePrefixMatch: /

tolerations:
  - key: "karpenter.sh/controller"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

env:
    configValue: "eks"