namespace: minecraft
server:
  replicas: 1
  scheduling:
    preferHighPerformanceNode: true
  bootstrap:
    imageHelperOpts: --http-response-timeout=PT5M --tls-handshake-timeout=PT1M
  image:
    repository: itzg/minecraft-server
    tag: java21
    pullPolicy: IfNotPresent
  port: 25565
  eula: "TRUE"
  type: NEOFORGE
  version: "1.21.1"
  curseforge:
    apiKeySecretName: minecraft-curseforge
    apiKeySecretKey: cf-api-key
  extraEnv:
    MOD_PLATFORM: AUTO_CURSEFORGE
    CF_API_KEY: ""
    CF_SLUG: all-the-mods-10-sky

persistence:
  claimName: minecraft-minecraft
  storageClass: longhorn
  size: 10Gi
service:
  name: minecraft
debug:
  deploymentName: mc-debug-ftp
  serviceName: mc-debug-ftp
  replicas: 0
  image:
    repository: fauria/vsftpd
    tag: latest
    pullPolicy: IfNotPresent
  ftp:
    user: minecraft
    authSecretName: mc-debug-ftp-auth
    passwordSecretKey: ftp-pass
    userSecretKey: ftp-user
    port: 21
    passiveAddress: 127.0.0.1
    passiveMinPort: 21100
    passiveMaxPort: 21105
route:
  enabled: true
  gatewayName: internal-gateway
  gatewayNamespace: ingress
  sectionName: minecraft
backup:
  schedule: "0 */6 * * *"
  suspend: false
  pvcName: minecraft-minecraft
  minioEndpoint: https://minio.minio.svc.cluster.local:9000
  minioBucket: minecraft-backups
  minioSecretName: minecraft-backup-minio
