{{- $root := . -}}
{{- $ingress := .Values.ingress | default dict -}}
{{- $hosts := get $ingress "hosts" | default list -}}
{{- $ingressTLS := get $ingress "tls" | default list -}}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: istio-system
  releaseName: prometheus
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      version: '*'
      sourceRef:
        kind: HelmRepository
        name: prometheus
  values:
    {{- with (first $hosts) }}
    {{- $host := .host -}}
    {{- with (first .paths) }}
    grafana:
      grafana.ini:
        server:
          root_url: "{{ if empty $ingressTLS }}http{{ else }}https{{ end }}://{{ $host }}{{ .path }}"
          serve_from_sub_path: true 
    {{- end }}
    {{- end }}
