[minio_external_pi]
localhost ansible_connection=local

[minio_external_pi_host]
svartalfheim ansible_host=192.168.8.177 ansible_user=oliver ansible_become=true

[minecraft_vm]
nidavellir ansible_host=192.168.8.126 ansible_user=ubuntu ansible_become=true

[kubernetes_manual_node]
midgard ansible_host=192.168.8.205 ansible_user=oliver ansible_become=true

[kubernetes_terraform_node]
jotunheim ansible_host=192.168.8.121 ansible_user=ubuntu ansible_become=true
alfheim ansible_host=192.168.8.122 ansible_user=ubuntu ansible_become=true
helheim ansible_host=192.168.8.123 ansible_user=ubuntu ansible_become=true
niflheim ansible_host=192.168.8.124 ansible_user=ubuntu ansible_become=true
