apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  interval: 1h
  targetNamespace: istio-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
  dependsOn:
    - name: istio-base
      namespace: flux-system