apiVersion: v2
name: external
description: Public Go API chart
type: application
version: 0.1.0
sources:
  - "https://github.com/labiraus/homelab"
appVersion: "1.16.0"

dependencies:
  - name: commonapi
    version: 1.0.0
    repository: file://../../libraries/commonapi
