ARG  BUILDER_IMAGE=golang:alpine
FROM ${BUILDER_IMAGE} AS builder

RUN apk update && apk add --no-cache git ca-certificates tzdata && update-ca-certificates
ENV APP_NAME=mcp

ENV USER=appuser
ENV UID=10001

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

WORKDIR $GOPATH/src/
COPY ./pkg/ ./pkg/

WORKDIR $GOPATH/src/$APP_NAME/
COPY $APP_NAME/go.mod $APP_NAME/go.sum ./
RUN go mod download

WORKDIR $GOPATH/src/$APP_NAME/
COPY $APP_NAME/. .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags='-w -s -extldflags "-static"' -a \
    -o /go/bin/app .

FROM scratch
EXPOSE 8080

LABEL org.opencontainers.image.source=https://github.com/labiraus/homelab

COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /etc/group /etc/group
COPY --from=builder /go/bin/app /go/bin/app

USER appuser:appuser

ENTRYPOINT ["/go/bin/app"]
