apiVersion: v2
name: envoy-ai-gateway
description: Install Envoy Gateway and Envoy AI Gateway controllers via Flux
type: application
version: 0.1.1

sources:
  - "https://github.com/labiraus/homelab"
