service:
  type: ClusterIP
  port: 3000
namespace: homelab
ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: mcp.labiraus.com
      paths:
        - path: /flagger
          pathType: PathPrefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - mcp.labiraus.com
