{{- if and .Values.namecheap.enabled .Values.namecheap.manageApiSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namecheap.apiSecretName }}
  namespace: {{ .Values.namecheap.webhookNamespace }}
type: Opaque
stringData:
  api-user: {{ .Values.namecheap.apiUser | quote }}
  api-key: {{ .Values.namecheap.apiKey | quote }}
  client-ip: {{ .Values.namecheap.clientIp | quote }}
{{- end }}
