# syntax=docker/dockerfile:1.7

ARG PYTHON_VERSION=3.13.12
FROM python:${PYTHON_VERSION}-slim-bookworm AS runtime

# Set the maintainer
LABEL org.opencontainers.image.source=https://github.com/labiraus/homelab

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

# Create a non-privileged user that the app will run under.
ARG UID=10001
ARG GID=10001
RUN groupadd --gid "${GID}" appuser \
    && useradd \
    --uid "${UID}" \
    --gid "${GID}" \
    --home-dir "/app" \
    --shell "/usr/sbin/nologin" \
    --no-create-home \
    appuser

COPY requirements.txt ./

RUN --mount=type=cache,target=/root/.cache/pip \
    python -m pip install --requirement requirements.txt

COPY --chown=appuser:appuser . .

# Expose the port that the application listens on.
EXPOSE 8080

USER appuser

CMD ["python", "app.py"]

