apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flux-system
spec:
  interval: 6h
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  targetNamespace: flagger-system
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
  values:
    nodeSelector:
      kubernetes.io/os: linux
