apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-env-configuration
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER={{ .Values.tenant.rootUser }}
    export MINIO_ROOT_PASSWORD={{ .Values.tenant.rootPassword }}
---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: {{ .Values.tenant.name }}
  namespace: {{ .Values.namespace }}
spec:
  image: {{ .Values.tenant.image }}
  pools:
    - servers: {{ .Values.tenant.pools.servers }}
      volumesPerServer: {{ .Values.tenant.pools.volumesPerServer }}
      volumeClaimTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: {{ .Values.tenant.pools.storageClassName }}
          resources:
            requests:
              storage: {{ .Values.tenant.pools.storage }}
  mountPath: /export
  requestAutoCert: false
  env:
    - name: MINIO_BROWSER_REDIRECT_URL
      value: {{ .Values.tenant.browserRedirectURL | quote }}
  configuration:
    name: minio-env-configuration
