---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart minecraft
  ansible.builtin.systemd_service:
    name: "{{ minecraft_vm_service_name }}"
    state: restarted
