name: App Processor CI/CD
on:
  repository_dispatch:
    types: [docker-build]
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Commit SHA to build
        required: false
        type: string
      trigger_reason:
        description: Why this workflow was invoked
        required: false
        type: string
  push:
    paths:
      - "apps/processor/**"
      - ".github/actions/docker/**"
      - ".github/workflows/app-processor.yml"

permissions:
  contents: read
  packages: write
  id-token: write

concurrency: ci-processor-docker-pipeline

jobs:
  test:
    name: "Processor Test"
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !contains(github.event.head_commit.message, 'no-ci')
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.commit_sha || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install
        working-directory: apps/processor

      - name: Run unit tests
        run: CI=true npm test
        working-directory: apps/processor

  ghcr:
    name: "Processor Build to GHCR"
    runs-on: ubuntu-latest
    environment: uat
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && !contains(github.event.head_commit.message, 'no-ci')

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.commit_sha || github.sha }}

      - name: Build to GHCR
        id: build
        uses: ./.github/actions/docker/ghcr
        with:
          dockerfile: ./apps/processor/dockerfile
          context: ./apps/processor
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: processor
          tag: uat

      - name: Publish Helm chart to GHCR
        uses: ./.github/actions/helm/ghcr
        with:
          chart: apps/processor
          token: ${{ secrets.GITHUB_TOKEN }}
          values: values-ghcr.yaml
          tag: uat
          app-version: ${{ steps.build.outputs.image_tag }}
