name: App External CI/CD
on:
  repository_dispatch:
    types: [docker-build]
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Commit SHA to build
        required: false
        type: string
      trigger_reason:
        description: Why this workflow was invoked
        required: false
        type: string
  push:
    paths:
      - "apps/external/**"
      - "apps/pkg/**"
      - ".github/actions/docker/**"
      - ".github/workflows/app-external.yml"

permissions:
  contents: read
  packages: write
  id-token: write

concurrency: ci-external-docker-pipeline

jobs:
  test:
    name: "External Test"
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !contains(github.event.head_commit.message, 'no-ci')

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.commit_sha || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.25.6'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('./apps/external/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: unit test
        run: go test ./apps/external/...

  ghcr:
    name: "External Build to GHCR"
    runs-on: ubuntu-latest
    environment: uat
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && !contains(github.event.head_commit.message, 'no-ci')

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.event.inputs.commit_sha || github.sha }}

      - name: Build to GHCR
        id: build
        uses: ./.github/actions/docker/ghcr
        with:
          dockerfile: ./apps/external/dockerfile
          context: ./apps
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: external
          tag: uat

      - name: Publish Helm chart to GHCR
        uses: ./.github/actions/helm/ghcr
        with:
          chart: apps/external
          token: ${{ secrets.GITHUB_TOKEN }}
          values: values-ghcr.yaml
          tag: uat
          app-version: ${{ steps.build.outputs.image_tag }}
