name: Helm Prometheus CI/CD
on:
  repository_dispatch:
    types: [helm-build]
  push:
    paths:
      - helm/infra/flux-prometheus/**/*
      - ".github/actions/helm/**"
      - ".github/workflows/helm-flux-prometheus.yml"

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  test-default:
    name: "Prometheus Helm Test Default"
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !contains(github.event.head_commit.message, 'no-ci')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
    
      - name: Test Default
        uses: ./.github/actions/helm/test
        with:
          chart: infra/flux-prometheus
          values: values.yaml

  test-ghcr:
    name: "Prometheus Helm Test GHCR"
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !contains(github.event.head_commit.message, 'no-ci')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
    
      - name: Test GHCR
        uses: ./.github/actions/helm/test
        with:
          chart: infra/flux-prometheus
          values: values-ghcr.yaml

  test-ecr:
    name: "Prometheus Helm Test ECR"
    runs-on: ubuntu-latest
    environment: uat
    if: github.ref != 'refs/heads/main' && !contains(github.event.head_commit.message, 'no-ci') && (vars.USE_ECR == 'true' || vars.USE_ECR == '')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
    
      - name: Test ECR
        uses: ./.github/actions/helm/test
        with:
          chart: infra/flux-prometheus
          values: values-ecr.yaml

  ghcr:
    name: "Prometheus Helm Build to GHCR"
    runs-on: ubuntu-latest
    environment: uat
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && !contains(github.event.head_commit.message, 'no-ci')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
    
      - name: Build to GHCR
        uses: ./.github/actions/helm/ghcr
        with:
          chart: infra/flux-prometheus
          token: ${{ secrets.GITHUB_TOKEN }}
          values: values-ghcr.yaml
          tag: uat

  ecr:
    name: "Prometheus Helm Build to ECR"
    runs-on: ubuntu-latest
    environment: uat
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'no-ci') && (vars.USE_ECR == 'true' || vars.USE_ECR == '')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
    
      - name: Build to ECR
        uses: ./.github/actions/helm/ecr
        with:
          chart: infra/flux-prometheus
          aws-region: ${{ vars.AWS_REGION}}
          role-to-assume: ${{ vars.OIDC_BUILD_ROLE}}
          registry: k8s-quickstart-ecr/helm-flux-prometheus
          values: values-ecr.yaml
          tag: uat
